### ISSUE TITLE
Card Info missing reviews when reschedule is undone

### ISSUE THREAD

**Issue by Jessieyang13** [lovac42/ReMemorize#19]
Hi,

I just installed the add-on and was trying to figure out exactly what it did to intervals, dues, and ease factors. I tried different input options (good, -90, 90) and kept undoing them to see what they did to card info. After a few tries I realized that the most recent review logs disappeared (missing 9/19/2019, 9/02/2019, now only shows everything before 8/27/2019). At the bottom of the card info pop-up, it says "Note: Some of the history is missing. For more information, please see the browser documentation." Ease factor wasn't changed (i didn't try changing it), nor was the interval actually. 10/31/2019 is 1.4month away from it's last review at 9/19/2019. That interval of 1.4 month is still there even tho the last review is shown as 8/27/2019.

I wasn't very successful at finding the browser documentation. Can I get some help?

**Comment by lovac42** [comment]
It sounds like you are looking at a different card info due to the way the reviews are randomized when you undo. Are you sure it's the same card? Could you match the card id?

To test this, disable all other addons to eliminate interference. Isolate a card into a single deck and retry what you did. Were you able to reproduce the error? Does the card id match?

**Comment by Jessieyang13** [comment]
Hi, I fixed the problem by using an older version of my collection I had backed-up before installing the Add-on.

However I thought it might be important to fix the problem if there is one, so here goes~ I'm quite certain it's the same card. I checked the card in preview, I matched all the dates, and I doubled checked the card ID.

I tried disabling the ReMemorize add-on, to no avail. Then I launched Anki while clicking shift key (disabling all add-ons and sync). That didn't solve the problem either. I think this extra bit of information points the problem away from the ReMemorize add-on. By this point, I used the back-up and fixed my problem.

I then followed your instructions (disabling other add-ons, isolating 1 card to a new deck). The problem was recreated. Here's what I did, step by step, and what happened.

1. check info of the card (last review 9/21, due today 11/1, interval 1.4m)
2. review the card and click "good" 
3. open browse + info (last last review 9/21, last review 11/1, due 2/8/2020, interval 3.3 m)
4. close info window + close browse
5. control Z to make the card unreviewed
6. open browse + info, reverted back to 1. (last review 9/21, due today 11/1, interval 1.4m)
7. close info + browse
8. review the card, control M, reschedule to -90
9. open browse + info (last review 9/21, due 1/30/2020, interval 1.4)
^see how today's (11/1) review is not logged
10. close info + close browse
11. control Z to make the card unreviewed
12. open browse + info (last review 9/2, due today 11/1, interval 1.4)
^see how 9/21 review is gone
it also comes with an additional sentence at the bottom of the info window:
"Note: Some of the history is missing. For more information, please see the browser documentation."

At this point I succeeded in recreating the problem so I imported a back up and undid the weird thing that happened above.

I hope this helps with something and thanks a bunch for replying!

**Comment by lovac42** [comment]
Thanks for the steps. It appears to be a regression when I added undo support for negative integer inputs. As negative inputs are not logged because they do not modify the interval, the undo feature of Anki appear to remove the last log entry regardless. The warning you receive at the bottom is only to tell you that the review count do not match the total number of log entries for the given card.

This does not affect the browser reposition feature in anyway as it reverts the state instead of the card. I will think about how to address this or whether to remove undo for negative inputs.

**Comment by lovac42** [comment]
The latest release should solve this issue, please test it and let me know. Thanks.
https://github.com/lovac42/ReMemorize/releases/tag/v1.2.1
