### ISSUE TITLE
allow search for cards rated other than 0, 1, 2, 3 or 4

### ISSUE THREAD

**Issue by galantra** [lovac42/ReMemorize#21]
Hi lovac,

This enhancement concerns the add-on "ReMemorize Buttons", too, and it's similar to #11 from ijgnord. 

I used to use ReMemorize buttons (I mean those that change the interval) for keys 5 and 6, and a reschedule button (-30 into the future, i.e. no interval change) for key 7.

I then created review buttons for the 7 and 8 keys. This made the reschedule button (-30) become key 9.

With this setup, I sometimes wanted to postpone a card by 30 days. I should do this with key 9 but out of habit I hit key 7. I only noticed this after about two week. Of course, I'd like to find those cards because they are scheduled much too far in the future.

I tried modifying ijgnord's great workaround and searching for `rated:31 -rated:31:1 -rated:31:2 -rated:31:3 -rated:31:4 -rated:31:0`. Unfortunately it returns nothing :/

Therefore, I suggest the idea to enhance _rated0Search_ so the browser parses queries like `rated:31:5` and `rated:31:8`. `rated:31:0` does not catch the cards.

**Comment by lovac42** [comment]
You can't because they are logged as regular reviews.

- Negative numbers change the due only, so they are not logged as reviews. You cannot use `rated:` here.
- Multipliers are graded as 1-4 depending on where they fit in.
So if you set a multiplier of 110% for button 5 and the ease bonus is 130%, the final interval will be between good and easy. This will be logged as grade 3 or Good.

There should be a way to search for these.... Or maybe we could flag them for easier searching later on. But your idea above isn't going to work.

**Comment by galantra** [comment]
Thank you for the explanation. I see. In my case, they would count as rated "4".

Maybe I'll export this and a backup to csv and compare the intervals… sth. like this

Thankfully it was only a handful of cards.
